services:
  frontend:
    image: ${DOCKER_USERNAME}/dream-vacation-app-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    image: ${DOCKER_USERNAME}/dream-vacation-app-backend:${IMAGE_TAG}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - COUNTRIES_API_BASE_URL=${COUNTRIES_API_BASE_URL}
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge