version: "3.8"

services:
  backend:
    image: ${DOCKER_USERNAME}/dream-backend:${BACKEND_TAG}
    container_name: dream-backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/dream-frontend:${FRONTEND_TAG}
    container_name: dream-frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:14
    container_name: dream-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
