services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
  backend:
    image: ${BACKEND_IMAGE}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - COUNTRIES_API_BASE_URL=${COUNTRIES_API_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
    driver: bridge