version: "3.9"

networks:
  app_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: ${DOCKER_USERNAME}/dream-backend:${IMAGE_TAG}
    container_name: backend
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    image: ${DOCKER_USERNAME}/dream-frontend:${IMAGE_TAG}
    container_name: frontend
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:
