services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_default

  backend:
    image: ${DOCKER_USERNAME}/dream-vacation-app-backend:${IMAGE_TAG}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_default

  frontend:
    image: ${DOCKER_USERNAME}/dream-vacation-app-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_default

networks:
  app_default:
    driver: bridge

volumes:
  postgres_data: