version: "3.8"
services:
  backend:
    image: ${BACKEND_IMAGE}
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    image: ${FRONTEND_IMAGE}
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: