name: Backend CI/CD

on:
  push:
    branches: [Ec2-deploy]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [Ec2-deploy]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - uses: docker/login-action@v3
        name: Docker Hub login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        name: Build & push backend image
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }}

      - uses: appleboy/scp-action@v0.1.7
        name: Upload docker-compose.base.yml to EC2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: docker-compose.base.yml
          target: /home/${{ secrets.EC2_USER }}/app

      - uses: appleboy/ssh-action@v1.0.3
        name: Deploy backend to EC2
        env:
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
          FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            mkdir -p /home/${{ secrets.EC2_USER }}/app/{backend,frontend}

            # Create or override .env files from GitHub Secrets
            cat > /home/${{ secrets.EC2_USER }}/app/backend/.env <<'EOF'
            ${BACKEND_ENV}
            EOF

            cat > /home/${{ secrets.EC2_USER }}/app/frontend/.env <<'EOF'
            ${FRONTEND_ENV}
            EOF

            # Install Docker and Compose if missing
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo usermod -aG docker $USER || true
            fi
            if ! command -v docker-compose >/dev/null 2>&1; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
                -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            cd /home/${{ secrets.EC2_USER }}/app

            # Always recreate docker-compose.yml from base
            cp docker-compose.base.yml docker-compose.yml
            sed -i "s|DOCKER_USERNAME_PLACEHOLDER|${DOCKER_USERNAME}|g" docker-compose.yml
            sed -i "s|REPLACE_BACKEND_TAG|${GITHUB_SHA}|g" docker-compose.yml
            sed -i "s|REPLACE_FRONTEND_TAG|bootstrap|g" docker-compose.yml
            echo "docker-compose.yml after replacements:"
            cat docker-compose.yml

            docker-compose pull db backend frontend || true
            docker-compose up -d db backend frontend
