name: Backend CI/CD

on:
  push:
    branches: [ Ec2-deploy ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repo

      - uses: docker/login-action@v3
        name: Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        name: Build & push backend image
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dream-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }}

      - uses: appleboy/scp-action@v0.1.7
        name: Upload docker-compose.yml to EC2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: docker-compose.yml
          target: /home/${{ secrets.EC2_USER }}/app/

      - uses: appleboy/ssh-action@v1.0.3
        name: Deploy on EC2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/app
            docker pull ${{ secrets.DOCKER_USERNAME }}/dream-backend:latest
            docker-compose up -d backend
