name: Backend CI/CD

on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - 'docker-compose.yml'
  pull_request:
    branches:
      - Ec2-deploy
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/dream-backend:latest

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "~/app"

      - name: SSH into EC2 and Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            touch .env
            grep -qxF "BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/dream-backend:${IMAGE_TAG}" .env || \
              sed -i "/^BACKEND_IMAGE=/d" .env && \
              echo "BACKEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/dream-backend:${IMAGE_TAG}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            docker compose pull backend
            docker compose up -d backend
