name: Deploy Backend

on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-backend:${GITHUB_SHA} backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/dream-backend:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/dream-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-backend:${GITHUB_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-backend:latest

      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/app/backend
            echo "${{ secrets.BACKEND_ENV_FILE }}" > /home/${{ secrets.EC2_USER }}/app/backend/.env
            cd /home/${{ secrets.EC2_USER }}/app
            IMAGE_TAG=${GITHUB_SHA} docker-compose pull backend
            IMAGE_TAG=${GITHUB_SHA} docker-compose up -d backend
