name: Build Backend

on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/build-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:${IMAGE_TAG} ./backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:latest

      - name: Push Backend Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-backend:latest