name: Deploy Backend
on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/app"

      - name: Deploy Backend + DB on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: IMAGE_TAG
          script: |
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app

            # Create .env file for docker-compose
            cat > .env <<EOF
            IMAGE_TAG=${IMAGE_TAG}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_PORT=5432
            COUNTRIES_API_BASE_URL=https://restcountries.com/v3.1
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
            EOF

            # Restart containers
            docker-compose pull backend
            docker-compose up -d backend db --remove-orphans
