name: Frontend CI/CD

on:
  push:
    branches: [ Ec2-deploy ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push frontend image (commit SHA + latest)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/dream-frontend:latest

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: docker-compose.yml
          target: /home/${{ secrets.EC2_USER }}/app

      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/app/frontend

            # Upload frontend .env from GitHub Secrets
            echo "${{ secrets.FRONTEND_ENV }}" > /home/${{ secrets.EC2_USER }}/app/frontend/.env

            cd /home/${{ secrets.EC2_USER }}/app
            docker-compose pull frontend
            docker-compose up -d frontend
