name: Build and Deploy Frontend to EC2
on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/frontend-deploy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Frontend Image
        run: |
          docker build --build-arg REACT_APP_API_URL=http://${{ secrets.EC2_PUBLIC_IP }}:3001 -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:${IMAGE_TAG} ./frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:latest
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      - name: Push Frontend Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-app-frontend:latest
      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/app"
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: IMAGE_TAG
          script: |
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app
            lockfile="/home/ubuntu/app/deploy.lock"
            for i in {1..30}; do
              if ! test -f "$lockfile"; then
                echo $$ > "$lockfile"
                break
              fi
              sleep 2
            done
            if test -f "$lockfile" && cat "$lockfile" | grep -q $$; then
              env_content="IMAGE_TAG=${IMAGE_TAG}
              DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
              POSTGRES_USER=${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
              POSTGRES_DB=${{ secrets.POSTGRES_DB }}
              POSTGRES_PORT=5432
              COUNTRIES_API_BASE_URL=https://restcountries.com/v3.1
              REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}"
              if [ ! -f .env ] || [ "$(cat .env)" != "$env_content" ]; then
                echo "$env_content" > .env
              fi
              whoami
              sudo docker ps -a
              for i in {1..30}; do
                if sudo docker inspect app-backend-1 | grep -q '"Status": "healthy"'; then
                  break
                fi
                if sudo docker ps | grep -q app-backend-1; then
                  break
                fi
                sleep 2
              done
              sudo docker rm -f app-frontend-1 || true
              sudo docker-compose -p app pull frontend
              sudo docker-compose -p app up -d frontend --remove-orphans
              sudo docker-compose -p app ps | grep "frontend.*Up" || { echo "Frontend container failed to start"; exit 1; }
              rm -f "$lockfile"
            else
              echo "Another deployment is in progress, exiting"
              exit 1
            fi