name: Deploy Frontend

on:
  push:
    branches: [ Ec2-deploy ]
    paths:
      - "frontend/**"
      - "docker-compose.yml"
      - ".github/workflows/frontend.yml"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${GITHUB_SHA} frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/dream-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${GITHUB_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-frontend:latest

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key_path: ec2_key.pem
          script: |
            cd ~/app
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
            echo "IMAGE_TAG=${GITHUB_SHA}" >> .env
            docker compose pull frontend
            docker compose up -d frontend
