name: Deploy Frontend

on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${GITHUB_SHA} frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${GITHUB_SHA} ${{ secrets.DOCKER_USERNAME }}/dream-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${GITHUB_SHA}
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-frontend:latest

      - name: Deploy frontend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/app/frontend
            echo "${{ secrets.FRONTEND_ENV_FILE }}" > /home/${{ secrets.EC2_USER }}/app/frontend/.env
            cd /home/${{ secrets.EC2_USER }}/app
            IMAGE_TAG=${GITHUB_SHA} docker-compose pull frontend
            IMAGE_TAG=${GITHUB_SHA} docker-compose up -d frontend
