name: Frontend CI/CD

on:
  push:
    branches:
      - Ec2-deploy
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - Ec2-deploy
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dream-frontend:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            touch .env
            # Remove only the old FRONTEND_IMAGE line and replace
            sed -i "/^FRONTEND_IMAGE=/d" .env
            echo "FRONTEND_IMAGE=${{ secrets.DOCKER_USERNAME }}/dream-frontend:${IMAGE_TAG}" >> .env

            # Ensure other env vars exist
            grep -qxF "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" .env || echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            grep -qxF "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" .env || echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            grep -qxF "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" .env || echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            grep -qxF "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" .env || echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env

            # Pull and restart only frontend
            docker-compose pull frontend
            docker-compose up -d frontend
